#!/bin/sh
set -e

install_toolchain() {
  echo "::group::Installing Rust"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  echo "::endgroup::"
  PATH="$HOME/.cargo/bin:$PATH"
  echo "::group::Installing cargo-contract"
  cargo install --locked cargo-contract --git https://github.com/kvinwang/cargo-contract --rev f332b2115b8aa1744bec243b8fcc48ab928ad5bc
  echo "::endgroup::"
}

build_contract() {
    echo "Building contract in $PWD"
    rm -rf .witness && mkdir -p .witness
    RUST_LOG=error cargo contract build --max-memory-pages 32 --release --output-json | tee .witness/output.json
    cd .witness
    jq -r '.metadata_result.dest_metadata' output.json | xargs -I % cp % metadata.json
    jq -r '.dest_wasm, .metadata_result.dest_bundle' output.json > contract_files.txt
    echo metadata.json >> contract_files.txt
    contract_name=$(jq -r '.contract.name' metadata.json)
    jq -r '.source.hash' metadata.json > contract_hash
    cat contract_files.txt | zip -@ -j $contract_name.zip
    echo "::notice title=witness.contract.$contract_name.packageHash::0x$(sha256sum $contract_name.zip | cut -d ' ' -f 1)"
    echo "::notice title=witness.contract.$contract_name.metadataHash::0x$(sha256sum metadata.json | cut -d ' ' -f 1)"
    echo "::notice title=witness.contract.$contract_name.wasmCodeHash::$(cat contract_hash)"
    mkdir -p $WITNESS_DIST_DIR
    cp $contract_name.zip $WITNESS_DIST_DIR/
}

if [ "$1" = "-i" ]; then
  install_toolchain
fi

build_contract
